SMSystem/Controllers/ExamController.cs
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Bibliography;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SMSystem.Helpers;
using SMSystem.Models;
using SMSystem.Models.Department;
using SMSystem.Models.Exam;
using SMSystem.Models.Fees;
using SMSystem.Repository.Interfaces;
using System.ComponentModel;
using System.Diagnostics;
using System.Security.Claims;

namespace SMSystem.Controllers
{
    [Authorize]
    public class ExamController : Controller
    {
        private readonly IExamRepository ExamRepo;

        public ExamController(IExamRepository ExamRepo)
        {
            this.ExamRepo = ExamRepo;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var response = new ExamPaggedViewModel();
                return View(response);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction("Index", "Home");
            }
        }

        public async Task<IActionResult> GetAll(SearchingParaModel para)
        {
            var response = new BaseResponseViewModel<ExamPaggedViewModel>();
            try
            {
                response = await ExamRepo.GetExams(para).ConfigureAwait(false);
                if (response.ResponseCode == 200)
                {
                    return PartialView("_ExamData", response.Result);
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return PartialView("_ExamData", response.Result);
                }
            }
            catch (Exception ex)
            {
                response.Result = new ExamPaggedViewModel();
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return PartialView("_ExamData", response.Result);
            }
        }

        public IActionResult ExportExcel()
        {
            try
            {
                var response = ExamRepo.GetAllExams();
                if (response.ResponseCode == 200)
                {
                    using (var wb = new XLWorkbook())
                    {
                        wb.Worksheets.Add(ConvertDataTable.Convert(response.Results));
                        using (var mstream = new MemoryStream())
                        {
                            wb.SaveAs(mstream);
                            return File(mstream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Exams.xlsx");
                        }
                    }
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return View("Index");
            }
        }

        [Authorize(Roles = "Admin , Teacher")]
        public async Task<IActionResult> Create()
        {
            try
            {
                return View();
            }
            catch(Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction("Index");
            }
        }

        [Authorize(Roles = "Admin , Teacher")]
        [HttpPost]
        public async Task<IActionResult> Create(ExamViewModel exam)
        {
            try
            {
                exam.CreatedBy = User.FindFirst(ClaimTypes.Name).Value;
                exam.ModifiedBy = User.FindFirst(ClaimTypes.Name).Value;
                var response = await ExamRepo.Add(exam);
                if (response.ResponseCode == 200)
                {
                    TempData["Message"] = "Record Created Successfully.";
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Create));
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction(nameof(Create));
            }
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var response = await ExamRepo.GetExam(id).ConfigureAwait(false);
                if (response.ResponseCode == 200)
                {
                    return View(response.Result);
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction(nameof(Index));
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(ExamViewModel exam)
        {
            try
            {
                exam.ModifiedBy = User.FindFirst(ClaimTypes.Name).Value;
                var response = await ExamRepo.Update(exam);
                if (response.ResponseCode == 200)
                {
                    TempData["Message"] = "Data saved successfully.";
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Edit));
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return View();
            }
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var para = new SearchingParaModel()
                {
                    PageIndex = 1
                };

                var response = await ExamRepo.Delete(id);

                var exams = await ExamRepo.GetExams(para).ConfigureAwait(false);
                return PartialView("_ExamData", exams.Result);
            }
            catch (Exception ex)
            {
                return Json(new { message = ex.Message, responseCode = 500 });
            }
        }
        
    }
}

SMSystem/Controllers/FeesController.cs
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Office2010.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SMSystem.Helpers;
using SMSystem.Models;
using SMSystem.Models.Department;
using SMSystem.Models.Exam;
using SMSystem.Models.Fees;
using SMSystem.Repository.Interfaces;
using System.Security.Claims;

namespace SMSystem.Controllers
{
    [Authorize]
    public class FeesController : Controller
    {
        private readonly IFeesRepository FeesRepo;

        public FeesController(IFeesRepository FeesRepo)
        {
            this.FeesRepo = FeesRepo;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var response = new FeesPaggedViewModel();
                return View(response);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction("Index", "Home");
            }
        }

        public async Task<IActionResult> GetAll(SearchingParaModel para)
        {
            var response = new BaseResponseViewModel<FeesPaggedViewModel>();
            try
            {
                response = await FeesRepo.GetFees(para).ConfigureAwait(false);
                if (response.ResponseCode == 200)
                {
                    return PartialView("_FeesData", response.Result);
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return PartialView("_FeesData", response.Result);
                }
            }
            catch (Exception ex)
            {
                response.Result = new FeesPaggedViewModel();
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return PartialView("_FeesData", response.Result);
            }
        }

        public IActionResult ExportExcel()
        {
            try
            {
                var response = FeesRepo.GetAllFees();
                if (response.ResponseCode == 200)
                {
                    using (var wb = new XLWorkbook())
                    {
                        wb.Worksheets.Add(ConvertDataTable.Convert(response.Results));
                        using (var mstream = new MemoryStream())
                        {
                            wb.SaveAs(mstream);
                            return File(mstream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Fees.xlsx");
                        }
                    }
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return View("Index");
            }
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            try
            {
                var fee = new FeesViewModel();
                var fees = FeesRepo.GetAllFees().Results;
                if (fees.Count > 0)
                {
                    var lastId = fees.OrderByDescending(x => x.FeesId).FirstOrDefault().FeesId;
                    char[] spearator = { '-', ' ' };
                    string[] feeId = lastId.Split(spearator, 2, StringSplitOptions.RemoveEmptyEntries);
                    int id = (Convert.ToInt32(feeId[1])) + 1;
                    fee.FeesId = "FEES-" + (id.ToString("0000"));
                }
                else
                {
                    fee.FeesId = "DEP-0001";
                }
                return View(fee);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction(nameof(Index));
            }
        }

        [Authorize(Roles ="Admin")]
        [HttpPost]
        public async Task<IActionResult> Create(FeesViewModel fee)
        {
            try
            {
                fee.CreatedBy = User.FindFirst(ClaimTypes.Name).Value;
                fee.ModifiedBy = User.FindFirst(ClaimTypes.Name).Value;
                var response = await FeesRepo.Add(fee);
                if (response.ResponseCode == 200)
                {
                    TempData["Message"] = "Record Created Successfully.";
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Create));
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction(nameof(Create));
            }
        }

        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var response = await FeesRepo.GetFee(id).ConfigureAwait(false);
                if (response.ResponseCode == 200)
                {
                    return View(response.Result);
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction(nameof(Index));
            }
        }

        [Authorize(Roles ="Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(FeesViewModel fee)
        {
            try
            {
                fee.ModifiedBy = User.FindFirst(ClaimTypes.Name).Value;
                var response = await FeesRepo.Update(fee);
                if (response.ResponseCode == 200)
                {
                    TempData["Message"] = "Data saved successfully.";
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Edit));
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return View();
            }
        }

        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var para = new SearchingParaModel()
                {
                    PageIndex = 1
                };

                var response = await FeesRepo.Delete(id);

                var fees = await FeesRepo.GetFees(para).ConfigureAwait(false);
                return PartialView("_ExamData", fees.Result);
            }
            catch (Exception ex)
            {
                return Json(new { message = ex.Message, responseCode = 500 });
            }
        }
    }
}

SMSystem/Views/Shared/_Footer.cshtml
<footer>
    <p>Copyright © 2023 DevR.</p>
</footer>

SMSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SMSystem</title>
    <link rel="shortcut icon" href="assets/img/favicon.png">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,700;0,900;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap/css/bootstrap.min.css">
    <link href="~/css/loader.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/assets/plugins/feather/feather.css">
    <link href="~/assets/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/assets/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" href="~/assets/plugins/icons/flags/flags.css">
    <link rel="stylesheet" href="~/assets/plugins/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="~/assets/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" href="~/assets/plugins/datatables/datatables.min.css">
    <link rel="stylesheet" href="~/assets/plugins/select2/css/select2.min.css">
    <link rel="stylesheet" href="~/assets/plugins/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" type="text/css" href="https://common.olemiss.edu/_js/sweet-alert/sweet-alert.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="~/assets/js/jquery-3.6.0.min.js"></script>
    <script>
        
        //$("#exception").addClass("show");
        


    </script>
</head>
<body>

    @* // Loader // *@
    <div id="overlay">

        <div class="cv-spinner">

            <span class="spinner"></span>

        </div>

    </div>

    <div class="main-wrapper">

        @{
            Html.RenderPartial("_Header");
        }

        @{
            Html.RenderPartial("_Sidebar");
        }

        <div class="page-wrapper">
            @{
                Html.RenderPartial("_Notification");
            }
            @RenderBody()

        </div>

    </div>
    <script>
        
        let responseCode = '@TempData["ResCode"]';
        var message = '@TempData["Message"]';
    </script>
    <script src="~/assets/js/jquery-3.6.0.min.js"></script>
    <script src="~/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/js/feather.min.js"></script>
    <script src="~/assets/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/assets/plugins/apexchart/apexcharts.min.js"></script>
    <script src="~/assets/plugins/datatables/datatables.min.js"></script>
    <script src="~/assets/plugins/apexchart/chart-data.js"></script>
    <script src="https://common.olemiss.edu/_js/sweet-alert/sweet-alert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="~/assets/plugins/moment/moment.min.js"></script>
    <script src="~/assets/plugins/select2/js/select2.min.js"></script>
    <script src="~/assets/js/bootstrap-datetimepicker.min.js"></script> 
    <script src="~/assets/js/script.js"></script>
    <script src="~/js/site.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SMSystem/Views/Shared/_Notification.cshtml
<div class="alert alert-danger alert-dismissible fade m-1" id="exception" role="alert">
    <strong>Error!</strong> <span id="ExcMsg"> </span>
</div>

SMSystem/Views/Shared/_Pagination.cshtml
@{
    var preDisable = !Model.PaggedModel.PreviousPage ? "disabled" : "";
    var nextDisable = !Model.PaggedModel.NextPage ? "disabled" : "";
    var pageIndex = Model.PaggedModel.PageIndex;
    var totalPage = Model.PaggedModel.TotalPage;
}
<div class="col-sm-12 col-md-5">
    <div class="mt-4">Showing page @pageIndex of @totalPage Pages.</div>
</div>
<div class="col-sm-12 col-md-7 ">
@using (Html.BeginForm())
{
    <div>
            <ul class="pagination mt-3 mb-4 justify-content-end">
            <li class="page-item @preDisable">
                <button type="button" value="@(pageIndex - 1)" class="page-link paggingBtn ">
                    Previous
                </button>
            </li>
            @for (var i = 1; i <= totalPage; i++)
            {
                <li id="currentIndex_@i" class="page-item"><button class="page-link paggingBtn " type="button" value="@i">@i</button></li>
            }
            <li class="page-item @nextDisable">
                <button type="button" value="@(pageIndex + 1)" class="page-link paggingBtn ">
                    Next
                </button>
            </li>
        </ul>
    </div>
}
</div>


<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script>
    var index = @pageIndex;
    var total = @totalPage;
    $('#currentIndex_' + index).addClass('active');
</script>

SMSystem/Views/Shared/_Sidebar.cshtml
<div>
    <div class="sidebar" id="sidebar">
        <div class="sidebar-inner slimscroll">
            <div id="sidebar-menu" class="sidebar-menu">
                <ul>
                    <li class="menu-title">
                        <span>Main Menu</span>
                    </li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li>
                            <a asp-action="Index" asp-controller="Home" class="loader">
                                <i class="feather-grid"></i> <span>Dashboard</span>
                            </a>
                        </li>
                    }
                    @if (User.IsInRole("Teacher"))
                    {
                        <li>
                            <a href="teacher-dashboard.html">
                                <i class="feather-grid"></i> <span>Dashboard</span>
                            </a>
                        </li>
                    }
                    @if (User.IsInRole("Student"))
                    {
                        <li>
                            <a href="student-dashboard.html">
                                <i class="feather-grid"></i> <span>Dashboard</span>
                            </a>
                        </li>
                    }
                        <li>
                            <a asp-action="Index" asp-controller="Student" class="loader">
                                <i class="fas fa-graduation-cap"></i> <span> Students</span>
                            </a>
                        </li>
                        <li>
                            <a asp-action ="Index" asp-controller="Teacher" class="loader">
                                <i class="fas fa-chalkboard-teacher"></i> <span> Teachers</span>
                            </a>
                        </li>
                    <li>
                        <a asp-action="Index" asp-controller="Department" class="loader">
                            <i class="fas fa-building"></i> <span> Departments</span>
                        </a>
                    </li>
                    <li>
                        <a asp-action ="Index" asp-controller="Subject" class="loader">
                            <i class="fas fa-book-reader"></i> <span> Subjects</span>
                        </a>
                    </li>
                    <li class="submenu">
                        <a href="#">
                            <i class="fas fa-clipboard"></i> <span> Invoices</span> <span class="menu-arrow"></span>
                        </a>
                        <ul>
                            <li><a href="invoices.html">Invoices List</a></li>
                            <li><a href="invoice-grid.html">Invoices Grid</a></li>
                            <li><a href="add-invoice.html">Add Invoices</a></li>
                            <li><a href="edit-invoice.html">Edit Invoices</a></li>
                            <li><a href="view-invoice.html">Invoices Details</a></li>
                            <li><a href="invoices-settings.html">Invoices Settings</a></li>
                        </ul>
                    </li>
                    <li class="menu-title">
                        <span>Management</span>
                    </li>
                    <li class="submenu">
                        <a href="#">
                            <i class="fas fa-file-invoice-dollar"></i> <span> Accounts</span> <span class="menu-arrow"></span>
                        </a>
                        <ul>
                            <li><a href="fees-collections.html">Fees Collection</a></li>
                            <li><a href="expenses.html">Expenses</a></li>
                            <li><a href="salary.html">Salary</a></li>
                            <li><a href="add-fees-collection.html">Add Fees</a></li>
                            <li><a href="add-expenses.html">Add Expenses</a></li>
                            <li><a href="add-salary.html">Add Salary</a></li>
                        </ul>
                    </li>
                    <li>
                        <a asp-action="Index" asp-controller="Holiday" class="loader"><i class="fas fa-holly-berry"></i> <span>Holiday</span></a>
                    </li>
                    <li>
                        <a asp-action="Index" asp-controller="Fees" class="loader"><i class="fas fa-comment-dollar"></i> <span>Fees</span></a>
                    </li>
                    <li>
                        <a asp-action="Index" asp-controller="Exam" class="loader"><i class="fas fa-clipboard-list"></i> <span>Exam list</span></a>
                    </li>
                    <li>
                        <a href="event.html"><i class="fas fa-calendar-day"></i> <span>Events</span></a>
                    </li>
                    <li>
                        <a href="time-table.html"><i class="fas fa-table"></i> <span>Time Table</span></a>
                    </li>
                    <li>
                        <a href="library.html"><i class="fas fa-book"></i> <span>Library</span></a>
                    </li>
                    <li class="submenu">
                        <a href="#">
                            <i class="fa fa-newspaper"></i> <span> Blogs</span>
                            <span class="menu-arrow"></span>
                        </a>
                        <ul>
                            <li><a href="blog.html">All Blogs</a></li>
                            <li><a href="add-blog.html">Add Blog</a></li>
                            <li><a href="edit-blog.html">Edit Blog</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="settings.html"><i class="fas fa-cog"></i> <span>Settings</span></a>
                    </li>
                    <li class="menu-title">
                        <span>Pages</span>
                    </li>
                    <li class="submenu">
                        <a href="#">
                            <i class="fas fa-shield-alt"></i> <span> Authentication </span> <span class="menu-arrow"></span>
                        </a>
                        <ul>
                            <li><a href="login.html">Login</a></li>
                            <li><a href="register.html">Register</a></li>
                            <li><a href="forgot-password.html">Forgot Password</a></li>
                            <li><a href="error-404.html">Error Page</a></li>
                        </ul>
                    </li>
                    <li>
                        <a asp-action="Privacy" asp-controller="Home" class="loader"><i class="fas fa-file"></i> <span>Blank Page</span></a>
                    </li>
                    <li class="menu-title">
                        <span>Others</span>
                    </li>
                    <li>
                        <a href="sports.html"><i class="fas fa-baseball-ball"></i> <span>Sports</span></a>
                    </li>
                    <li>
                        <a href="hostel.html"><i class="fas fa-hotel"></i> <span>Hostel</span></a>
                    </li>
                    <li>
                        <a href="transport.html"><i class="fas fa-bus"></i> <span>Transport</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>