SMSystem/Models/Student/StudentPagedViewModel.cs
using SMSystem.Models.Department;

namespace SMSystem.Models.Students
{
    public class StudentPagedViewModel
    {
        public StudentPagedViewModel()
        {
            StudentModel = new List<StudentViewModel>();
            PaggedModel = new PaggedViewModel();
        }
        public List<StudentViewModel> StudentModel { get; set; }
        public PaggedViewModel PaggedModel { get; set; }
    }
}

SMSystem/Models/Student/StudentRegisterViewModel.cs
using SMSystem.Models.Auth;
using SMSystem.Models.Students;

namespace SMSystem.Models.Student
{
    public class StudentRegisterViewModel
    {
        public StudentViewModel StudentModel { get; set; }
        public ApplicationUser UserModel { get; set; }
    }
}

SMSystem/Models/Student/StudentViewModel.cs
using Microsoft.AspNetCore.Mvc;
using SMSystem.Helpers;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SMSystem.Models.Students
{
    public class StudentViewModel : BaseEntityViewModel
    {
        [Key]
        public int Id { get; set; }
        public string StudentId { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "The First Name is required.")]
        public string FirstName { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "The Parent Name is required.")]
        public string ParentName { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "The Last Name is required.")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "The Gender is required to select.")]
        public string Gender { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "The Date of Birth is required.")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime DateOfBirth { get; set; }
        [Required(ErrorMessage = "The Roll No is required.")]
        public string RollNo { get; set; }
        [Required(ErrorMessage = "The Blood Group is required to select.")]
        public string BloodGroup { get; set; }
        [Required(ErrorMessage = "The Religion is required to select.")]
        public string Religion { get; set; }
        [Required(ErrorMessage = "The Class is required to select.")]
        public string Class { get; set; }
        [Required(ErrorMessage = "The Section is required to select.")]
        public string Section { get; set; }
        [Required(ErrorMessage = "The Admission Id is required.")]
        public string AdmissionId { get; set; }
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "The Phone is required.")]
        [RegularExpression(@"^(\d{10})$", ErrorMessage = "Not a valid phone number.")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "The Address is required.")]
        public string Address { get; set; }
        public string? Path { get; set; }
        [NotMapped]
        [Display(Name = "Choose Image")]
        public IFormFile? ImagePath { get; set; }
    }
}

SMSystem/Controllers/StudentController.cs
using Azure;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.Win32;
using Newtonsoft.Json;
using SMSystem.Helpers;
using SMSystem.Models;
using SMSystem.Models.Department;
using SMSystem.Models.Student;
using SMSystem.Models.Students;
using SMSystem.Repository.Interfaces;
using System.Collections;
using System.Configuration;
using System.Data;
using System.Reflection;
using System.Security.Claims;
using static Microsoft.VisualStudio.Services.Graph.GraphResourceIds;

namespace SMSystem.Controllers
{
    [Authorize]
    public class StudentController : Controller
    {
        private readonly IStudentRepository StdRepo;

        public StudentController(IStudentRepository repository)
        {
            StdRepo = repository;
        }

        // Index
        public async Task<IActionResult> Index(SearchingParaModel para)
        {
            try
            {
                var response = new StudentPagedViewModel();
                return View(response);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction("Index", "Home");
            }
        }

        public async Task<IActionResult> GridIndex()
        {
            try
            {
                var response = StdRepo.GetAllStudents();
                if (response.ResponseCode == 200)
                {
                    return View(response.Results);
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction("Index");
            }
        }

        // Returning data to the view
        public async Task<IActionResult> GetAll(SearchingParaModel para)
        {
            var response = new BaseResponseViewModel<StudentPagedViewModel>();
            try
            {
                response = await StdRepo.GetStudents(para).ConfigureAwait(false);
                if (response.ResponseCode == 200)
                {
                    return PartialView("_StudentData", response.Result);
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return PartialView("_StudentData", response.Result);
                }
            }
            catch (Exception ex)
            {
                response.Result = new StudentPagedViewModel();
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return PartialView("_StudentData", response.Result);
            }
        }

        [Authorize(Roles ="Admin , Teacher")]
        public IActionResult ExportExcel()
        {
            try
            {
                var response = StdRepo.GetAllStudents();
                if (response.ResponseCode == 200)
                {
                    using (var wb = new XLWorkbook())
                    {
                        wb.Worksheets.Add(ConvertDataTable.Convert(response.Results));
                        using (var mstream = new MemoryStream())
                        {
                            wb.SaveAs(mstream);
                            return File(mstream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Students.xlsx");
                        }
                    }
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction("Index");
            }
        }

        // GET: StudentController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var response = await StdRepo.GetStudent(id).ConfigureAwait(false);
                if (response.ResponseCode == 200)
                {
                    return View(response.Result);
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: StudentController/Create
        [Authorize(Roles ="Admin , Teacher")]
        public async Task<IActionResult> Create()
        {
            try
            {
                
                var student = new StudentViewModel();
                var students = StdRepo.GetAllStudents().Results;
                if (students.Count > 0)
                {
                    var lastId = students.OrderByDescending(x => x.StudentId).FirstOrDefault().StudentId;
                    char[] spearator = { '-', ' ' };
                    string[] stdId = lastId.Split(spearator, 2, StringSplitOptions.RemoveEmptyEntries);
                    int id = (Convert.ToInt32(stdId[1])) + 1;
                    student.StudentId = "STD-" + (id.ToString("0000"));
                }
                else
                {
                    student.StudentId = "STD-0001";
                }
                var register = new StudentRegisterViewModel()
                {
                    StudentModel = student,
                    UserModel = new Models.Auth.ApplicationUser()
                };
                return View(register);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: StudentController/Create
        [Authorize(Roles ="Admin , Teacher")]
        [HttpPost]
        public async Task<IActionResult> Create(StudentRegisterViewModel register)
        {
            try
            {
                register.UserModel.Name = register.StudentModel.FirstName;
                register.StudentModel.CreatedBy = User.FindFirst(ClaimTypes.Name).Value;
                register.StudentModel.ModifiedBy = User.FindFirst(ClaimTypes.Name).Value;
                var response = await StdRepo.Add(register);
                if (response.ResponseCode == 200)
                {
                    TempData["Message"] = "Record Created Successfully.";
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Create));
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return View();
            }
        }

        // GET: StudentController/Edit/5
        [Authorize(Roles ="Admin , Teacher")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var response = await StdRepo.GetStudent(id).ConfigureAwait(false);
                if (response.ResponseCode == 200)
                {
                    return View(response.Result);
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: StudentController/Edit/5
        [Authorize(Roles ="Admin , Teacher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(StudentViewModel student)
        {
            try
            {
                student.ModifiedBy = User.FindFirst(ClaimTypes.Name).Value;
                var response = await StdRepo.Update(student);
                if (response.ResponseCode == 200)
                {
                    TempData["Message"] = "Data saved successfully.";
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Edit));
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return View();
            }
        }

        // POST: StudentController/Delete/5
        [Authorize(Roles ="Admin , Teacher")]
        [HttpPost]

SMSystem/Views/Student/Details.cshtml
@model SMSystem.Models.Students.StudentViewModel


<div class="content container-fluid">
    <div class="page-header">
        <div class="row">
            <div class="col-sm-12">
                <div class="page-sub-header">
                    <h3 class="page-title">Student Details</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-controller="Student" asp-action="Index" class="loader">All Student</a></li>
                        <li class="breadcrumb-item active">Student Details</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="about-info">
                        <h4>Profile <span><a href="javascript:;"><i class="feather-more-vertical"></i></a></span></h4>
                    </div>
                    <div class="student-profile-head">
                        <div class="profile-bg-img">
                            <img src="~/assets/img/profile-bg.jpg" alt="Profile">
                        </div>
                        <div class="row">
                            <div class="col-lg-4 col-md-4">
                                <div class="profile-user-box">
                                    <div class="profile-user-img">
                                        <img src="@Model.Path" alt="Profile">
                                    </div>
                                    <div class="names-profiles">
                                        <h4>
                                            @Html.DisplayFor(model => model.FirstName)
                                            @Html.DisplayFor(model => model.LastName)
                                        </h4>
                                        <h5>
                                            Student
                                        </h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-4 d-flex align-items-center">
                                <div class="follow-group">
                                    <div class="students-follows">
                                        <h5>Followers</h5>
                                        <h4>2850</h4>
                                    </div>
                                    <div class="students-follows">
                                        <h5>Followers</h5>
                                        <h4>2850</h4>
                                    </div>
                                    <div class="students-follows">
                                        <h5>Followers</h5>
                                        <h4>2850</h4>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-4 d-flex align-items-center">
                                <div class="follow-btn-group">
                                    <button type="submit" class="btn btn-info follow-btns">Follow</button>
                                    <button type="submit" class="btn btn-info message-btns">Message</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="student-personals-grp">
                        <div class="card">
                            <div class="card-body">
                                <div class="heading-detail">
                                    <h4>Personal Details :</h4>
                                </div>
                                <div class="personal-activity">
                                    <div class="personal-icons">
                                        <i class="feather-user"></i>
                                    </div>
                                    <div class="views-personal">
                                        <h4>Name</h4>
                                        <h5>
                                            @Html.DisplayFor(model => model.FirstName)
                                            @Html.DisplayFor(model => model.LastName)
                                        </h5>
                                    </div>
                                </div>
                                <div class="personal-activity">
                                    <div class="personal-icons">
                                        <i class="feather-phone-call"></i>
                                    </div>
                                    <div class="views-personal">
                                        <h4>Mobile</h4>
                                        <h5>
                                            @Html.DisplayFor(model => model.Phone)
                                        </h5>
                                    </div>
                                </div>
                                <div class="personal-activity">
                                    <div class="personal-icons">
                                        <i class="feather-user"></i>
                                    </div>
                                    <div class="views-personal">
                                        <h4>Gender</h4>
                                        <h5>
                                            @Html.DisplayFor(model => model.Gender)
                                        </h5>
                                    </div>
                                </div>
                                <div class="personal-activity">
                                    <div class="personal-icons">
                                        <i class="feather-calendar"></i>
                                    </div>
                                    <div class="views-personal">
                                        <h4>Date of Birth</h4>
                                        <h5>
                                            @Html.DisplayFor(model => model.DateOfBirth)
                                        </h5>
                                    </div>
                                </div>
                                <div class="personal-activity">
                                    <div class="personal-icons">
                                        <i class="feather-italic"></i>
                                    </div>
                                    <div class="views-personal">
                                        <h4>Language</h4>
                                        <h5>English, French, Bangla</h5>
                                    </div>
                                </div>
                                <div class="personal-activity mb-0">
                                    <div class="personal-icons">
                                        <i class="feather-map-pin"></i>
                                    </div>
                                    <div class="views-personal">
                                        <h4>Address</h4>
                                        <h5>
                                            @Html.DisplayFor(model => model.Address)
                                        </h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="student-personals-grp">
                        <div class="card mb-0">
                            <div class="card-body">
                                <div class="heading-detail">
                                    <h4>Skills:</h4>
                                </div>
                                <div class="skill-blk">
                                    <div class="skill-statistics">
                                        <div class="skills-head">
                                            <h5>Photoshop</h5>
                                            <p>90%</p>
                                        </div>
                                        <div class="progress mb-0">
                                            <div class="progress-bar bg-photoshop" role="progressbar" style="width: 90%" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
                                        </div>
                                    </div>
                                    <div class="skill-statistics">
                                        <div class="skills-head">
                                            <h5>Code editor</h5>
                                            <p>75%</p>
                                        </div>
                                        <div class="progress mb-0">
                                            <div class="progress-bar bg-editor" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                                        </div>
                                    </div>
                                    <div class="skill-statistics mb-0">
                                        <div class="skills-head">
                                            <h5>Illustrator</h5>
                                            <p>95%</p>
                                        </div>
                                        <div class="progress mb-0">
                                            <div class="progress-bar bg-illustrator" role="progressbar" style="width: 95%" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="student-personals-grp">
                        <div class="card mb-0">
                            <div class="card-body">
                                <div class="heading-detail">
                                    <h4>About Me</h4>
                                </div>
                                <div class="hello-park">
                                    <h5>Hello I am Daisy Parks</h5>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur officia deserunt mollit anim id est laborum.</p>
                                    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. </p>
                                </div>
                                <div class="hello-park">
                                    <h5>Education</h5>
                                    <div class="educate-year">
                                        <h6>2008 - 2009</h6>
                                        <p>Secondary Schooling at xyz school of secondary education, Mumbai.</p>
                                    </div>
                                    <div class="educate-year">
                                        <h6>2011 - 2012</h6>
                                        <p>Higher Secondary Schooling at xyz school of higher secondary education, Mumbai.</p>
                                    </div>
                                    <div class="educate-year">
                                        <h6>2012 - 2015</h6>
                                        <p>Bachelor of Science at Abc College of Art and Science, Chennai.</p>
                                    </div>
                                    <div class="educate-year">
                                        <h6>2015 - 2017</h6>
                                        <p class="mb-0">Master of Science at Cdm College of Engineering and Technology, Pune.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@{
    Html.RenderPartial("_Footer");
}

SMSystem/Views/Student/GridIndex.cshtml
@model IEnumerable<SMSystem.Models.Students.StudentViewModel>

@{
    ViewData["Title"] = "GridIndex";
}



<div class="content container-fluid">

    <div class="page-header">
        <div class="row">
            <div class="col-sm-12">
                <div class="page-sub-header">
                    <h3 class="page-title">Students</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index" class="loader">Dashboard</a></li>
                        <li class="breadcrumb-item active">All Students</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card card-table comman-shadow">
                <div class="card-body pb-0">

                    <div class="page-header">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="page-title">Students</h3>
                            </div>
                            <div class="col-auto text-end float-end ms-auto download-grp">
                                <a asp-controller="Student" asp-action="Index" class="btn btn-outline-gray me-2 loader"><i class="feather-list"></i></a>
                                <a asp-controller="Student" asp-action="GridIndex" class="btn btn-outline-gray me-2 active loader"><i class="feather-grid "></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="student-pro-list">
                        <div class="row">
                            @foreach (var item in Model)
                            {
                                <div class="col-xl-3 col-lg-4 col-md-6 d-flex">
                                    <div class="card">
                                        <div class="card-body">
                                            <div class="student-box flex-fill">
                                                <div class="student-img">
                                                    <a asp-controller="Student" asp-action="Details" asp-route-id="@item.Id">
                                                        <img class="img-fluid" alt="Students Info" src="@item.Path" height="200px" width="200px">
                                                    </a>
                                                </div>
                                                <div class="student-content pb-0">
                                                    <h5><a asp-controller="Student" asp-action="Details" asp-route-id="@item.Id">@item.FirstName @item.LastName</a></h5>
                                                    <h6>Student</h6>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>