SMSystem/Models/Teacher/TeacherPagedViewModel.cs
using SMSystem.Models.Department;
using SMSystem.Models.Students;

namespace SMSystem.Models.Teacher
{
    public class TeacherPagedViewModel
    {
        public TeacherPagedViewModel()
        {
            TeacherModel = new List<TeacherViewModel>();
            PaggedModel = new PaggedViewModel();
        }
        public List<TeacherViewModel> TeacherModel { get; set; }
        public PaggedViewModel PaggedModel { get; set; }
    }
}

SMSystem/Models/Teacher/TeacherRegisterViewModel.cs
using SMSystem.Models.Auth;

namespace SMSystem.Models.Teacher
{
    public class TeacherRegisterViewModel
    {
        public TeacherViewModel TeacherModel { get; set; }
        public ApplicationUser UserModel { get; set; }
    }
}

SMSystem/Models/Teacher/TeacherViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SMSystem.Models.Teacher
{
    public class TeacherViewModel : BaseEntityViewModel
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [Display(Name = "Teacher Id")]
        public string TeacherId { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        [Display(Name="Date Of Birth")]
        public DateTime DateOfBirth { get; set; }
        [Required]
        [Display(Name= "Phone No")]
        [RegularExpression(@"^(\d{10})$", ErrorMessage = "Not a valid phone number.")]
        public string PhoneNo { get; set; }
        [Required]
        public string Subject { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Joining Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime JoiningDate { get; set; }
        [Required]
        public string Qualification { get; set; }
        [Required]
        public string Experience { get; set; }
        public string? Path { get; set; }
        [NotMapped]
        [Display(Name = "Choose Image")]
        public IFormFile? ImagePath { get; set; }
        [Required]
        [Display(Name = "Address")]
        public string AddressLine1 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        [Required]
        public string PostalCode { get; set; }
        [Required]
        public string Country { get; set; }
    }
}

SMSystem/Controllers/TeacherController.cs
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Win32;
using SMSystem.Helpers;
using SMSystem.Models;
using SMSystem.Models.Students;
using SMSystem.Models.Teacher;
using SMSystem.Repository.Interfaces;
using System.Security.Claims;

namespace SMSystem.Controllers
{
    [Authorize]
    public class TeacherController : Controller
    {
        private readonly ITeacherRepository TeachRepo;

        public TeacherController(ITeacherRepository TeachRepo)
        {
            this.TeachRepo = TeachRepo;
        }

        // GET: TeacherController
        public async Task<IActionResult> Index(SearchingParaModel para)
        {
            try
            {
                var response = new TeacherPagedViewModel();
                return View(response);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction("Index", "Home");
            }
        }

        public async Task<IActionResult> GridIndex()
        {
            try
            {
                var response = TeachRepo.GetAllTeachers();
                if (response.ResponseCode == 200)
                {
                    return View(response.Results);
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction("Index");
            }
        }

        // Returning data to the view
        public async Task<IActionResult> GetAll(SearchingParaModel para)
        {
            var response = new BaseResponseViewModel<TeacherPagedViewModel>();
            try
            {
                response = await TeachRepo.GetTeachers(para).ConfigureAwait(false);
                if (response.ResponseCode == 200)
                {
                    return PartialView("_TeacherData", response.Result);
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return PartialView("_TeacherData", response.Result);
                }
            }
            catch (Exception ex)
            {
                response.Result = new TeacherPagedViewModel();
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return PartialView("_TeacherData", response.Result);
            }
        }

        [Authorize(Roles = "Admin")]
        public IActionResult ExportExcel()
        {
            try
            {
                var response = TeachRepo.GetAllTeachers();
                if (response.ResponseCode == 200)
                {
                    using (var wb = new XLWorkbook())
                    {
                        wb.Worksheets.Add(ConvertDataTable.Convert(response.Results));
                        using (var mstream = new MemoryStream())
                        {
                            wb.SaveAs(mstream);
                            return File(mstream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Teachers.xlsx");
                        }
                    }
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction("Index");
            }
        }

        // GET: TeacherController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var response = await TeachRepo.GetTeacher(id).ConfigureAwait(false);
                if (response.ResponseCode == 200)
                {
                    return View(response.Result);
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: TeacherController/Create
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            try
            {
                var teacher = new TeacherViewModel();
                var teachers = TeachRepo.GetAllTeachers().Results;
                if (teachers.Count > 0)
                {
                    var lastId = teachers.OrderByDescending(x => x.TeacherId).FirstOrDefault().TeacherId;
                    char[] spearator = { '-', ' ' };
                    string[] tchId = lastId.Split(spearator, 2, StringSplitOptions.RemoveEmptyEntries);
                    int id = (Convert.ToInt32(tchId[1])) + 1;
                    teacher.TeacherId = "TCHR-" + (id.ToString("0000"));
                }
                else
                {
                    teacher.TeacherId = "TCHR-0001";
                }
                var register = new TeacherRegisterViewModel()
                {
                    TeacherModel = teacher,
                    UserModel = new Models.Auth.ApplicationUser()
                };
                return View(register);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: TeacherController/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create(TeacherRegisterViewModel register)
        {
            try
            {
                register.UserModel.Name = register.TeacherModel.Name;
                register.TeacherModel.ModifiedBy = User.FindFirst(ClaimTypes.Name).Value;
                register.TeacherModel.ModifiedBy = User.FindFirst(ClaimTypes.Name).Value;
                var response = await TeachRepo.Add(register);
                if (response.ResponseCode == 200)
                {
                    TempData["Message"] = "Record Created Successfully.";
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Create));
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return View();
            }
        }

        // GET: TeacherController/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var response = await TeachRepo.GetTeacher(id).ConfigureAwait(false);
                if (response.ResponseCode == 200)
                {
                    return View(response.Result);
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: TeacherController/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TeacherViewModel teacher)
        {
            try
            {
                teacher.ModifiedBy = User.FindFirst(ClaimTypes.Name).Value;
                var response = await TeachRepo.Update(teacher);
                if (response.ResponseCode == 200)
                {
                    TempData["Message"] = "Data saved successfully.";
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Edit));
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return View();
            }
        }

        // POST: TeacherController/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var para = new SearchingParaModel()
                {
                    SId = string.Empty,
                    Name = string.Empty,
                    Year = string.Empty,
                    PageIndex = 1

SMSystem/Views/Teacher/Create.cshtml
@model SMSystem.Models.Teacher.TeacherRegisterViewModel
@using SMSystem.Helpers.DropdownHelper;


@{
    ViewData["Title"] = "Create";
}


<div class="content container-fluid">

    <div class="page-header">
        <div class="row align-items-center">
            <div class="col">
                <h3 class="page-title">Add Teachers</h3>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-controller="Teacher" asp-action="Index" class="loader">Teachers</a></li>
                    <li class="breadcrumb-item active">Add Teachers</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <form asp-action="Create" enctype="multipart/form-data">
                        <div class="row">
                            <div class="col-12">
                                <h5 class="form-title"><span>Basic Details</span></h5>
                            </div>
                            <div class="col-12 col-sm-4">
                                <div class="form-group local-forms">
                                    <label asp-for="TeacherModel.TeacherId">Teacher ID <span class="login-danger">*</span></label>
                                    <div class="input-group">
                                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                                        <input asp-for="TeacherModel.TeacherId" class="form-control" value="@Model.TeacherModel.TeacherId" hidden />
                                        <input class="form-control" value="@Model.TeacherModel.TeacherId" disabled />
                                    </div>
                                    <span asp-validation-for="TeacherModel.TeacherId" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12 col-sm-4">
                                <div class="form-group local-forms">
                                    <label asp-for="TeacherModel.Name">Name <span class="login-danger">*</span></label>
                                    <input asp-for="TeacherModel.Name" type="text" class="form-control" placeholder="Enter Name" />
                                    <span asp-validation-for="TeacherModel.Name" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12 col-sm-4">
                                <div class="form-group local-forms">
                                    <label asp-for="TeacherModel.Gender">Gender <span class="login-danger">*</span></label>
                                    <select class="form-control select" asp-for="TeacherModel.Gender" asp-items="EnumHelper.GetEnumSelectList<Gender>()">
                                        <option value="">Select Gender</option>
                                    </select>
                                    <span asp-validation-for="TeacherModel.Gender" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12 col-sm-4">
                                <div class="form-group local-forms calendar-icon">
                                    <label asp-for="TeacherModel.DateOfBirth">Date Of Birth <span class="login-danger">*</span></label>
                                    <input asp-for="TeacherModel.DateOfBirth" class="form-control datetimepicker" type="datetime" placeholder="DD-MM-YYYY" autocomplete="off" value="" />
                                    <span asp-validation-for="TeacherModel.DateOfBirth" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12 col-sm-4">
                                <div class="form-group local-forms">
                                    <label asp-for="TeacherModel.PhoneNo">Mobile <span class="login-danger">*</span></label>
                                    <input asp-for="TeacherModel.PhoneNo" type="text" class="form-control" placeholder="Enter Phone" />
                                    <span asp-validation-for="TeacherModel.PhoneNo" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12 col-sm-4">
                                <div class="form-group local-forms">
                                    <label asp-for="TeacherModel.Subject">Subject <span class="login-danger">*</span></label>
                                    <input asp-for="TeacherModel.Subject" type="text" class="form-control" placeholder="Enter Subject" />
                                    <span asp-validation-for="TeacherModel.Subject" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12 col-sm-4">
                                <div class="form-group local-forms calendar-icon">
                                    <label asp-for="TeacherModel.JoiningDate">Joining Date <span class="login-danger">*</span></label>
                                    <input asp-for="TeacherModel.JoiningDate" class="form-control datetimepicker" type="datetime" placeholder="DD-MM-YYYY" autocomplete="off" value="" />
                                    <span asp-validation-for="TeacherModel.JoiningDate" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12 col-sm-4">
                                <div class="form-group local-forms">
                                    <label asp-for="TeacherModel.Qualification">Qualification <span class="login-danger">*</span></label>
                                    <input asp-for="TeacherModel.Qualification" class="form-control" type="text" placeholder="Enter Qualification" />
                                    <span asp-validation-for="TeacherModel.Qualification" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12 col-sm-4">
                                <div class="form-group local-forms">
                                    <label asp-for="TeacherModel.Experience">Experience <span class="login-danger">*</span></label>
                                    <input asp-for="TeacherModel.Experience" class="form-control" type="text" placeholder="Enter Experience" />
                                    <span asp-validation-for="TeacherModel.Experience" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group students-up-files">
                                    <label asp-for="TeacherModel.ImagePath">Upload Student Photo (150px X 150px)</label>
                                    <div class="uplod">
                                        <label class="file-upload image-upbtn mb-0">
                                            Choose File <input type="file" asp-for="TeacherModel.ImagePath">
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <br />
                            <div class="col-12">
                                <h5 class="form-title"><span>Login Details</span></h5>
                            </div>
                            <input asp-for="UserModel.UserId" class="form-control" value="@Model.TeacherModel.TeacherId" hidden />
                            <div class="col-12 col-sm-6">
                                <div class="form-group local-forms">
                                    <label asp-for="UserModel.Username">Username <span class="login-danger">*</span></label>
                                    <input type="text" asp-for="UserModel.Username" class="form-control" placeholder="Enter Username">
                                    <span asp-validation-for="UserModel.Username" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12 col-sm-6">
                                <div class="form-group local-forms">
                                    <label asp-for="UserModel.Email">Email ID <span class="login-danger">*</span></label>
                                    <input type="email" asp-for="UserModel.Email" class="form-control" placeholder="Enter Mail Id">
                                    <span asp-validation-for="UserModel.Email" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12 col-sm-6">
                                <div class="form-group local-forms">
                                    <label asp-for="UserModel.Password">Password <span class="login-danger">*</span></label>
                                    <input type="text" asp-for=UserModel.Password class="form-control" placeholder="Enter Password">
                                    <span asp-validation-for="UserModel.Password" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12 col-sm-6">
                                <div class="form-group local-forms">
                                    <label asp-for="UserModel.RepeatPassword">Confirm Password <span class="login-danger">*</span></label>
                                    <input type="text" asp-for="UserModel.RepeatPassword" class="form-control" placeholder="Confirm Password">
                                    <span asp-validation-for="UserModel.RepeatPassword" class="text-danger"></span>
                                </div>
                            </div>
                            <br />
                            <div class="col-12">
                                <h5 class="form-title"><span>Address</span></h5>
                            </div>
                            <div class="col-12">
                                <div class="form-group local-forms">
                                    <label asp-for="TeacherModel.AddressLine1">Address <span class="login-danger">*</span></label>
                                    <input asp-for="TeacherModel.AddressLine1" type="text" class="form-control" placeholder="Enter address" />
                                    <span asp-validation-for="TeacherModel.AddressLine1" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12 col-sm-6">
                                <div class="form-group local-forms">
                                    <label asp-for="TeacherModel.City">City</label>
                                    <input asp-for="TeacherModel.City" type="text" class="form-control" placeholder="Enter City" />
                                </div>
                            </div>
                            <div class="col-12 col-sm-6">
                                <div class="form-group local-forms">
                                    <label asp-for="TeacherModel.State">State</label>
                                    <input asp-for="TeacherModel.State" type="text" class="form-control" placeholder="Enter State" />
                                </div>
                            </div>
                            <div class="col-12 col-sm-6">
                                <div class="form-group local-forms">
                                    <label asp-for="TeacherModel.PostalCode">Zip Code <span class="login-danger">*</span></label>
                                    <input asp-for="TeacherModel.PostalCode" type="text" class="form-control" placeholder="Enter Zip" />
                                    <span asp-validation-for="TeacherModel.PostalCode" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12 col-sm-6">
                                <div class="form-group local-forms">
                                    <label asp-for="TeacherModel.Country">Country <span class="login-danger">*</span></label>
                                    <input asp-for="TeacherModel.Country" type="text" class="form-control" placeholder="Enter Country" />
                                    <span asp-validation-for="TeacherModel.Country" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="student-submit">
                                    <button type="submit" class="btn btn-primary loader">Submit</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

SMSystem/Views/Teacher/GridIndex.cshtml
@model IEnumerable<SMSystem.Models.Teacher.TeacherViewModel>

@{
    ViewData["Title"] = "GridIndex";
}

<div class="content container-fluid">

    <div class="page-header">
        <div class="row">
            <div class="col-sm-12">
                <div class="page-sub-header">
                    <h3 class="page-title">Teachers</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index" class="loader">Dashboard</a></li>
                        <li class="breadcrumb-item active">Teachers</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card card-table comman-shadow">
                <div class="card-body pb-0">

                    <div class="page-header">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="page-title">Teachers</h3>
                            </div>
                            <div class="col-auto text-end float-end ms-auto download-grp">
                                <a asp-controller="Teacher" asp-action="Index" class="btn btn-outline-gray me-2 loader"><i class="feather-list"></i></a>
                                <a asp-controller="Teacher" asp-action="GridIndex" class="btn btn-outline-gray me-2 active loader"><i class="feather-grid "></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="student-pro-list">
                        <div class="row">
                            @foreach (var item in Model)
                            {
                                <div class="col-xl-3 col-lg-4 col-md-6 d-flex">
                                    <div class="card">
                                        <div class="card-body">
                                            <div class="student-box flex-fill">
                                                <div class="student-img">
                                                    <a asp-controller="Teacher" asp-action="Details" asp-route-id="@item.Id">
                                                        <img class="img-fluid" alt="Teachers Info" src="@item.Path" height="200px" width="200px">
                                                    </a>
                                                </div>
                                                <div class="student-content pb-0">
                                                    <h5><a asp-controller="Teacher" asp-action="Details" asp-route-id="@item.Id">@item.Name</a></h5>
                                                    <h6>Teacher</h6>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>