SMSystem/Models/Subject/SubjectPaggedViewModel.cs
using SMSystem.Models.Department;

namespace SMSystem.Models.Subject
{
    public class SubjectPaggedViewModel
    {
        public SubjectPaggedViewModel()
        {
            SubjectModel = new List<SubjectViewModel>();
            PaggedModel = new PaggedViewModel();
        }
        public IList<SubjectViewModel> SubjectModel { get; set; }
        public PaggedViewModel PaggedModel { get; set; }
    }
}

SMSystem/Models/Subject/SubjectViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SMSystem.Models.Subject
{
    public class SubjectViewModel : BaseEntityViewModel
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string SubjectId { get; set; }
        [Required]
        public string SubjectName { get; set; }
        [Required]
        public string Class { get; set; }
    }
}

SMSystem/Controllers/SubjectController.cs
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Win32;
using SMSystem.Helpers;
using SMSystem.Models;
using SMSystem.Models.Department;
using SMSystem.Models.Subject;
using SMSystem.Repository.Interfaces;
using System.Security.Claims;
using static Microsoft.VisualStudio.Services.Graph.GraphResourceIds;

namespace SMSystem.Controllers
{
    [Authorize]
    public class SubjectController : Controller
    {
        private readonly ISubjectRepository SubRepo;

        public SubjectController(ISubjectRepository SubRepo)
        {
            this.SubRepo = SubRepo;
        }

        // GET: DepartmentController
        public async Task<IActionResult> Index(SearchingParaModel para)
        {
            try
            {
                var response = new SubjectPaggedViewModel();
                return View(response);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction("Index", "Home");
            }
        }

        public async Task<IActionResult> GetAll(SearchingParaModel para)
        {
            var response = new BaseResponseViewModel<SubjectPaggedViewModel>();
            try
            {
                response = await SubRepo.GetSubjects(para).ConfigureAwait(false);
                if (response.ResponseCode == 200)
                {
                    return PartialView("_SubjectData", response.Result);
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return PartialView("_SubjectData", response.Result);
                }
            }
            catch (Exception ex)
            {
                response.Result = new SubjectPaggedViewModel();
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return PartialView("_SubjectData", response.Result);
            }
        }

        public IActionResult ExportExcel()
        {
            try
            {
                var response = SubRepo.GetAllSubjects();
                if (response.ResponseCode == 200)
                {
                    using (var wb = new XLWorkbook())
                    {
                        wb.Worksheets.Add(ConvertDataTable.Convert(response.Results));
                        using (var mstream = new MemoryStream())
                        {
                            wb.SaveAs(mstream);
                            return File(mstream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Subjects.xlsx");
                        }
                    }
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction("Index");
            }
        }

        [Authorize(Roles = "Admin")]
        // GET: DepartmentController/Create
        public async Task<IActionResult> Create()
        {
            try
            {
                var subject = new SubjectViewModel();
                var subjects = SubRepo.GetAllSubjects().Results;
                if (subjects.Count > 0)
                {
                    var lastId = subjects.OrderByDescending(x => x.SubjectId).FirstOrDefault().SubjectId;
                    char[] spearator = { '-', ' ' };
                    string[] subId = lastId.Split(spearator, 2, StringSplitOptions.RemoveEmptyEntries);
                    int id = (Convert.ToInt32(subId[1])) + 1;
                    subject.SubjectId = "SUB-" + (id.ToString("0000"));
                }
                else
                {
                    subject.SubjectId = "SUB-0001";
                }

                return View(subject);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction(nameof(Index));
            }
        }

        [Authorize(Roles = "Admin")]
        // POST: DepartmentController/Create
        [HttpPost]
        public async Task<IActionResult> Create(SubjectViewModel subject)
        {
            try
            {
                subject.ModifiedBy = User.FindFirst(ClaimTypes.Name).Value;
                subject.ModifiedBy = User.FindFirst(ClaimTypes.Name).Value;
                var response = await SubRepo.Add(subject);
                if (response.ResponseCode == 200)
                {
                    TempData["Message"] = "Record Created Successfully.";
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Create));
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return View();
            }
        }

        [Authorize(Roles = "Admin")]
        // GET: DepartmentController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var response = await SubRepo.GetSubject(id).ConfigureAwait(false);
                if (response.ResponseCode == 200)
                {
                    return View(response.Result);
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return RedirectToAction(nameof(Index));
            }
        }

        [Authorize(Roles = "Admin")]
        // POST: DepartmentController/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(SubjectViewModel subject)
        {
            try
            {
                subject.ModifiedBy = User.FindFirst(ClaimTypes.Name).Value;
                var response = await SubRepo.Update(subject);
                if (response.ResponseCode == 200)
                {
                    TempData["Message"] = "Data saved successfully.";
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["Message"] = response.Message;
                    TempData["ResCode"] = response.ResponseCode;
                    return RedirectToAction(nameof(Edit));
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                TempData["ResCode"] = 500;
                return View();
            }
        }

        [Authorize(Roles = "Admin")]
        // POST: DepartmentController/Delete/5
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var para = new SearchingParaModel()
                {
                    SId = string.Empty,
                    Name = string.Empty,
                    Year = string.Empty,
                    PageIndex = 1
                };

                var response = await SubRepo.Delete(id);

                var subjects = await SubRepo.GetSubjects(para).ConfigureAwait(false);
                return PartialView("_SubjectData", subjects.Result);
            }
            catch (Exception ex)
            {
                return Json(new { message = ex.Message, responseCode = 500 });
            }
        }
    }
}

SMSystem/Views/Subject/Create.cshtml
@model SMSystem.Models.Subject.SubjectViewModel
@using SMSystem.Helpers.DropdownHelper;

<div class="content container-fluid">

    <div class="page-header">
        <div class="row align-items-center">
            <div class="col">
                <h3 class="page-title">Add Subject</h3>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-action="Index" class="loader">Subject</a></li>
                    <li class="breadcrumb-item active">Add Subject</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <form asp-action="Create">
                        <div class="row">
                            <div class="col-12">
                                <h5 class="form-title"><span>Subject Information</span></h5>
                            </div>
                            <div class="col-12 col-sm-4">
                                <div class="form-group local-forms">
                                    <label asp-for="SubjectId">Subject ID <span class="login-danger">*</span></label>
                                    <div class="input-group">
                                        <span class="input-group-text"></span>
                                        <input class="form-control" value="@Model.SubjectId" disabled />
                                    </div>
                                        <input asp-for="SubjectId" class="form-control" value="@Model.SubjectId" hidden />
                                    <span asp-validation-for="SubjectId" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12 col-sm-4">
                                <div class="form-group local-forms">
                                    <label asp-for="SubjectName">Subject Name <span class="login-danger">*</span></label>
                                    <input asp-for="SubjectName" type="text" class="form-control" />
                                    <span asp-validation-for="SubjectName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12 col-sm-4">
                                <div class="form-group local-forms">
                                    <label asp-for="Class">Class <span class="login-danger">*</span></label>
                                    <select class="form-control select" asp-for="Class" asp-items="EnumHelper.GetEnumSelectList<Class>()">
                                        <option value="">Please Select Class </option>
                                    </select>
                                    <span asp-validation-for="Class" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="student-submit">
                                    <button type="submit" class="btn btn-primary loader">Create</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

SMSystem/Views/Subject/Edit.cshtml
@model SMSystem.Models.Subject.SubjectViewModel
@using SMSystem.Helpers.DropdownHelper;


<div class="content container-fluid">

    <div class="page-header">
        <div class="row align-items-center">
            <div class="col">
                <h3 class="page-title">Edit Subject</h3>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-action="Index" class="loader">Subject</a></li>
                    <li class="breadcrumb-item active">Edit Subject</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <form asp-action="Edit">
                        <div class="row">
                            <div class="col-12">
                                <h5 class="form-title"><span>Subject Information</span></h5>
                            </div>
                            <input asp-for="Id" class="form-control" value="@Model.Id" hidden>
                            <div class="col-12 col-sm-4">
                                <div class="form-group local-forms">
                                    <label asp-for="SubjectId">Subject ID <span class="login-danger">*</span></label>
                                    <div class="input-group">
                                        <span class="input-group-text"></span>
                                        <input class="form-control" value="@Model.SubjectId" disabled />
                                    </div>
                                        <input asp-for="SubjectId" class="form-control" value="@Model.SubjectId" hidden />
                                    <span asp-validation-for="SubjectId" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12 col-sm-4">
                                <div class="form-group local-forms">
                                    <label asp-for="SubjectName">Subject Name <span class="login-danger">*</span></label>
                                    <input asp-for="SubjectName" type="text" class="form-control" />
                                    <span asp-validation-for="SubjectName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12 col-sm-4">
                                <div class="form-group local-forms">
                                    <label asp-for="Class">Class <span class="login-danger">*</span></label>
                                    <select class="form-control select" asp-for="Class" asp-items="EnumHelper.GetEnumSelectList<Class>()">
                                        <option value="">Please Select Class </option>
                                    </select>
                                    <span asp-validation-for="Class" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="student-submit">
                                    <button type="submit" class="btn btn-primary loader">Submit</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

SMSystem/Views/Subject/Index.cshtml
@model SMSystem.Models.Subject.SubjectPaggedViewModel

@{
    ViewData["Title"] = "Index";
}

<div class="content container-fluid">

    <div class="page-header">
        <div class="row align-items-center">
            <div class="col">
                <h3 class="page-title">Subjects</h3>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-controller ="Home" asp-action="Index" class="loader">Dashboard</a></li>
                    <li class="breadcrumb-item loader" asp-controller="Subject" asp-action="Index">All Subjects</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="student-group-form">
        <div class="row">
            <div class="col-lg-4 col-md-6">
                <div class="form-group">
                    <input type="text" id="sub_Id" class="form-control" onkeyup="searchingSub()" placeholder="Search by ID ...">
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="form-group">
                    <input type="text" id="sub_Name" class="form-control" onkeyup="searchingSub()" placeholder="Search by Name ...">
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="form-group">
                    <input type="text" id="sub_Class" class="form-control" onkeyup="searchingSub()" placeholder="Search by Class ...">
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="card card-table">
                <div class="card-body">

                    <div class="page-header">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="page-title">Subjects</h3>
                            </div>
                            <div class="col-auto text-end float-end ms-auto download-grp">
                                <a asp-action="ExportExcel" asp-controller="Subject" id="Export-Sub" class="btn btn-outline-primary me-2"><i class="fas fa-download"></i> Download</a>
                                @if (User.IsInRole("Admin"))
                                {
                                    <a asp-action="Create" asp-controller="Subject" class="btn btn-primary"><i class="fas fa-plus"></i></a>
                                }
                            </div>
                        </div>
                    </div>
                    <div id="SubjectData">
                        <div id="overlay">
                            <div class="cv-spinner">
                                <span class="spinner"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/js/subject.js"></script>
<script>
    $(document).ready(function () {
        let url = "/Subject/GetAll";
        let element = "#SubjectData";
        let obj = {
            SId: $("#sub_Id").val(),
            Name: $("#sub_Name").val(),
            Class: $("#sub_Class").val(),
            PageIndex: 1
        };
        GetData(obj, url, element);
    });
</script>

SMSystem/Views/Subject/_SubjectData.cshtml
@model SMSystem.Models.Subject.SubjectPaggedViewModel


<div class="table-responsive">
    <div class="row">
        <div class="col-sm-12">
            <table class="table border-0 star-student table-hover table-center mb-0 table-striped">
                <thead class="student-thread">
                    <tr>
                        <th>
                            <div class="form-check check-tables">
                                <input class="form-check-input" type="checkbox" value="something">
                            </div>
                        </th>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Class</th>
                        @if (User.IsInRole("Admin"))
                        { 
                            <th class="text-end">Action</th>
                        }
                    </tr>
                </thead>
                <tbody>
                     @if (Model.SubjectModel.Count > 0)
                    {
                        @foreach (var item in Model.SubjectModel)
                        {
                            <tr>
                                <td>
                                    <div class="form-check check-tables">
                                        <input class="form-check-input" type="checkbox" value="something">
                                    </div>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SubjectId)
                                </td>
                                <td>
                                    <h2>
                                        @Html.DisplayFor(modelItem => item.SubjectName)
                                    </h2>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Class)
                                </td>
                                @if (User.IsInRole("Admin"))
                                { 
                                <td class="text-end">
                                    <div class="actions">
                                        <a asp-controller="Subject" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm bg-danger-light me-2 loader">
                                            <i class="feather-edit"></i>
                                        </a>
                                        <a value="@item.Id" id="dlt_subject" class="btn btn-sm bg-success-light me-2">
                                            <i class="feather-trash-2"></i>
                                        </a>
                                    </div>
                                </td>
                                }

                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="9" class="text-center">
                                <h3 style="color:red;">
                                    No Data Found!
                                </h3>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div id="paginationData" class="row">
    @{
        Html.RenderPartial("_Pagination");
    }
</div>
<script type="text/javascript">
    responseCode = '@TempData["ResCode"]';
    message = '@TempData["Message"]';

    if (responseCode != 200 && responseCode != '') {
        $("#ExcMsg").append(message);
        $("#exception").addClass("show");
        setTimeout("$('#exception').removeClass('show');", 4000);
        setTimeout("$('#ExcMsg').removeText();", 4000);

        $.fn.removeText = function () {
            this.each(function () {

                // Get elements contents
                var $cont = $(this).contents();

                // Loop through the contents
                $cont.each(function () {
                    var $this = $(this);

                    // If it's a text node
                    if (this.nodeType == 3) {
                        $this.remove(); // Remove it
                    } else if (this.nodeType == 1) { // If its an element node
                        $this.removeText(); //Recurse
                    }
                });
            });
        }
    }
</script>